// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVInsHlkK8N6S25DSq5e7z6MAm3EaekbI',
    appId: '1:420047980243:web:62e2b488ba279d40ce3626',
    messagingSenderId: '420047980243',
    projectId: 'stem-b2191',
    authDomain: 'stem-b2191.firebaseapp.com',
    storageBucket: 'stem-b2191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv1hsHTP2xy47WqPxPPp_b1dZMlVWpvVk',
    appId: '1:420047980243:android:8c331f0f56ce0f8dce3626',
    messagingSenderId: '420047980243',
    projectId: 'stem-b2191',
    storageBucket: 'stem-b2191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekx56KGOJYbh5HoEBGubeCC7ksYjY5g0',
    appId: '1:420047980243:ios:aa6df720852927d8ce3626',
    messagingSenderId: '420047980243',
    projectId: 'stem-b2191',
    storageBucket: 'stem-b2191.firebasestorage.app',
    iosBundleId: 'com.example.stamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekx56KGOJYbh5HoEBGubeCC7ksYjY5g0',
    appId: '1:420047980243:ios:aa6df720852927d8ce3626',
    messagingSenderId: '420047980243',
    projectId: 'stem-b2191',
    storageBucket: 'stem-b2191.firebasestorage.app',
    iosBundleId: 'com.example.stamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVInsHlkK8N6S25DSq5e7z6MAm3EaekbI',
    appId: '1:420047980243:web:64702c7e2603772dce3626',
    messagingSenderId: '420047980243',
    projectId: 'stem-b2191',
    authDomain: 'stem-b2191.firebaseapp.com',
    storageBucket: 'stem-b2191.firebasestorage.app',
  );
}
